### ISSUE TITLE
Why is service restart on config change disabled?

### ISSUE THREAD

**Issue by blalor** [echocat/puppet-mongodb#7]
https://github.com/echocat/puppet-mongodb/blob/master/manifests/init.pp#L70

Why is the notify disabled?  Is there a known issue with mongo and config changes?

**Comment by pulecp** [comment]
@dwerder everyone has always different approach and manages different stacks which requires different care etc. Someone doesn't want to run mongo with different configuration than it's in config file. Because what will happen when you restart mongo after 2 years? You won't remember what you did.

Your arguments are correct but mine as well imho. I think that there should be an option to enable the notify of mongo in the case of some config change. This option can be disabled by default of course. I'm going to create PR for that soon.

**Comment by dwerder** [comment]
I agree and its an opensource project. Send in a PR if you like.
